import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { pathToFileURL } from 'node:url';
const name='202609050002_managed_caption_sessions.sql';
const read = () => readFile(new URL(`../supabase/migrations/${name}`, import.meta.url),'utf8');
test('managed caption metadata is service-only and bootstrap mirrored', async () => {
  const sql=await read();
  const bootstrap=await readFile(new URL('../supabase/bootstrap-new-project.sql',import.meta.url),'utf8');
  assert.ok(bootstrap.includes(`-- supabase/migrations/${name}\n\n${sql}`));
  assert.match(sql,/enable row level security/);
  assert.match(sql,/interval '6 hours'/);
  assert.doesNotMatch(sql,/audio|transcript/);
});
test('caption authority pins assignment, denies cross-owner/revoked/expired use and makes stop terminal', {skip:!process.env.NOVA_PGLITE_MODULE},async(t)=>{
  const {PGlite}=await import(pathToFileURL(process.env.NOVA_PGLITE_MODULE).href);
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`create role anon;create role authenticated;create role service_role;
    create table profiles(host_id text primary key,status text,voice_provider text,voice_provider_revision bigint);
    insert into profiles values('owner','approved','soniox',1),('other','approved','gemini',1);`);
  await db.exec(await read());await db.exec(await read());
  const id='00000000-0000-4000-8000-000000000001';
  const engine={stt:{provider:'soniox',model:'stt-rt-v5'},translation:{provider:'soniox',model:'stt-rt-v5'},summary:{provider:'gemini',model:'gemini-3.6-flash'}};
  const create=(revision='1',providerEngine=engine,languages=['ko','en','ja'])=>db.query('select create_managed_caption_session_v1($1,$2,$3,$4,$5)',[id,'owner',providerEngine,revision,languages]);
  await assert.rejects(create('2'),/ASSIGNMENT_CONFLICT/);
  await assert.rejects(create('1',{...engine,stt:{provider:'gemini',model:'gemini-3.5-transcribe-live'}}),/ASSIGNMENT_CONFLICT/);
  await assert.rejects(create('1',engine,['ko','ko']),/INVALID/);
  await create();
  await db.exec("update profiles set voice_provider='gemini',voice_provider_revision=2 where host_id='owner'");
  const pinned=(await db.query('select * from read_managed_caption_session_v1($1,$2)',[id,'owner'])).rows[0];
  assert.deepEqual(pinned.engine,engine);assert.equal(pinned.assignment_revision,'1');assert.deepEqual(pinned.languages,['ko','en','ja']);
  assert.equal((await db.query('select * from read_managed_caption_session_v1($1,$2)',[id,'other'])).rows.length,0);
  await db.query('select renew_managed_caption_session_v1($1,$2)',[id,'owner']);
  await assert.rejects(db.query('select renew_managed_caption_session_v1($1,$2)',[id,'other']),/FORBIDDEN/);
  await db.exec("update profiles set status='disabled' where host_id='owner'");
  assert.equal((await db.query('select * from read_managed_caption_session_v1($1,$2)',[id,'owner'])).rows.length,0);
  await assert.rejects(db.query('select renew_managed_caption_session_v1($1,$2)',[id,'owner']),/FORBIDDEN/);
  await db.exec("update profiles set status='approved' where host_id='owner'");
  assert.equal((await db.query('select stop_managed_caption_session_v1($1,$2) as stopped',[id,'other'])).rows[0].stopped,false);
  for(let i=0;i<2;i++)assert.equal((await db.query('select stop_managed_caption_session_v1($1,$2) as stopped',[id,'owner'])).rows[0].stopped,true);
  assert.equal((await db.query('select * from read_managed_caption_session_v1($1,$2)',[id,'owner'])).rows.length,0);
  await assert.rejects(db.query('select renew_managed_caption_session_v1($1,$2)',[id,'owner']),/FORBIDDEN/);
  await assert.rejects(create('2'),/ASSIGNMENT_CONFLICT/);
  const second='00000000-0000-4000-8000-000000000002';
  await db.exec("update profiles set voice_provider='soniox',voice_provider_revision=3 where host_id='owner'");
  await assert.rejects(create('3'), /duplicate key/);
  assert.equal((await db.query('select status from managed_caption_sessions where id=$1',[id])).rows[0].status,'stopped');
  await db.query('select create_managed_caption_session_v1($1,$2,$3,$4,$5)',[second,'owner',engine,'3',['ko']]);
  await db.query("update managed_caption_sessions set access_expires_at=now()-interval '1 second' where id=$1",[second]);
  assert.equal((await db.query('select * from read_managed_caption_session_v1($1,$2)',[second,'owner'])).rows.length,0);
  await db.exec("update profiles set voice_provider='gemini',voice_provider_revision=4 where host_id='owner'");
  await db.query('select renew_managed_caption_session_v1($1,$2)',[second,'owner']);
  const restored=(await db.query('select * from read_managed_caption_session_v1($1,$2)',[second,'owner'])).rows[0];
  assert.deepEqual(restored.engine,engine);assert.equal(restored.assignment_revision,'3');
  await db.query("update managed_caption_sessions set access_expires_at=now()-interval '7 hours' where id=$1",[second]);
  await db.exec("update profiles set status='disabled' where host_id='owner'");
  await assert.rejects(db.query('select renew_managed_caption_session_v1($1,$2)',[second,'owner']),/FORBIDDEN/);
  await db.exec("update profiles set status='approved' where host_id='owner'");
  await db.query('select stop_managed_caption_session_v1($1,$2)',[second,'owner']);
  await assert.rejects(db.query('select renew_managed_caption_session_v1($1,$2)',[second,'owner']),/FORBIDDEN/);
});
