import fs from "node:fs/promises";
import { createReadStream } from "node:fs";
import { randomUUID } from "node:crypto";
import { pipeline } from "node:stream/promises";
import os from "node:os";
import path from "node:path";

export function getNovaConfigPaths(homeDir = os.homedir()) {
  const configDir = path.join(homeDir, ".config", "nova");
  return { configDir, settingsPath: path.join(configDir, "settings.json"), transcriptsDir: path.join(configDir, "transcripts") };
}

async function ensureDirectory(directory) {
  await fs.mkdir(directory, { recursive: true, mode: 0o700 });
  if (!(await fs.lstat(directory)).isDirectory()) throw new Error("NOVA configuration requires a regular directory.");
}

async function readLegacyJson(source) {
  try {
    if (!(await fs.lstat(source)).isFile()) return null;
    const content = await fs.readFile(source, "utf8");
    try { return JSON.parse(content); }
    catch { throw new Error("기존 NOVA 데이터의 JSON 형식을 확인해주세요."); }
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

async function writeJsonOnce(destination, data) {
  try {
    await fs.writeFile(destination, JSON.stringify(data, null, 2) + "\n", { flag: "wx", mode: 0o600 });
  } catch (error) {
    if (error.code !== "EEXIST") throw error;
  }
}

async function copySettingsOnce(source, destination) {
  try { await fs.lstat(destination); return; }
  catch (error) { if (error.code !== "ENOENT") throw error; }
  const legacy = await readLegacyJson(source);
  if (!legacy || typeof legacy !== "object" || Array.isArray(legacy)) return;
  const settings = Object.fromEntries(["subtitle", "subtitleHistory", "apiKeys"]
    .filter((key) => Object.hasOwn(legacy, key)).map((key) => [key, legacy[key]]));
  await writeJsonOnce(destination, settings);
}

async function copyAudioOnce(source, destination) {
  const temporary = `${destination}.${randomUUID()}.import`;
  try {
    if (!(await fs.lstat(source)).isFile()) return;
    const output = await fs.open(temporary, "wx", 0o600);
    try {
      await pipeline(createReadStream(source), output.createWriteStream());
      await fs.link(temporary, destination);
    } finally {
      await output.close();
    }
  } catch (error) {
    if (error.code !== "ENOENT" && error.code !== "EEXIST") throw error;
  } finally {
    await fs.rm(temporary, { force: true });
  }
}

async function copyCaptionTranscriptsOnce(source, destination) {
  let entries;
  try {
    if (!(await fs.lstat(source)).isDirectory()) return;
    entries = await fs.readdir(source, { withFileTypes: true });
  } catch (error) {
    if (error.code === "ENOENT") return;
    throw error;
  }
  await ensureDirectory(destination);
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".json") || entry.name.endsWith(".meta.json")) continue;
    const record = await readLegacyJson(path.join(source, entry.name));
    if (!record || !["local", "live-call"].includes(record.kind)
      || typeof record.id !== "string" || !record.id
      || typeof record.startedAt !== "string" || !Number.isFinite(Date.parse(record.startedAt))
      || entry.name !== `${encodeURIComponent(record.id)}.json`
      || !Array.isArray(record.lines)
      || record.lines.some((line) => !line || typeof line.sourceText !== "string" || typeof line.translatedText !== "string")) continue;
    // Caption metadata is regenerated by session-transcripts; unrelated canvas JSON stays behind.
    await writeJsonOnce(path.join(destination, entry.name), record);
    for (const lane of ["mic", "system"]) {
      for (const extension of ["wav", "pcm"]) {
        const fileName = `${encodeURIComponent(record.id)}.${lane}.${extension}`;
        const audioPath = path.join(source, fileName);
        await copyAudioOnce(audioPath, path.join(destination, fileName));
      }
    }
  }
}

export async function migrateNovaConfig({ homeDir = os.homedir() } = {}) {
  const paths = getNovaConfigPaths(homeDir);
  await ensureDirectory(paths.configDir);
  const markerPath = path.join(paths.configDir, ".legacy-import-complete");
  try {
    await fs.lstat(markerPath);
    return paths;
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  // 2026-09-05 fix: Import once without deleting canvas data or restoring records deleted in NOVA.
  for (const legacyName of ["realtime-noel", "autopreso"]) {
    const legacyDir = path.join(homeDir, ".config", legacyName);
    await copySettingsOnce(path.join(legacyDir, "settings.json"), paths.settingsPath);
    await copyCaptionTranscriptsOnce(path.join(legacyDir, "transcripts"), paths.transcriptsDir);
  }
  try {
    await fs.writeFile(markerPath, "1\n", { flag: "wx", mode: 0o600 });
  } catch (error) {
    if (error.code !== "EEXIST") throw error;
  }
  return paths;
}
